### ISSUE TITLE
chain-link hackathon

### ISSUE THREAD

**Issue by thisispalash** [the-world-if/concept#11]
### Submission Criteria :: 4/11 2359 EDT
- 5 minute video
- source code
- description
- working-demo?
- why did you choose a particular layer1 or layer2 solution?
  - polkadot :: logo? shards now vs eth later
  - plasm :: vs moonbeam, no layer2 on moonbeam

## Schedule

[x] 3/15 :: opening ceremony
[ ] 3/25 :: midway check-in starts
[ ] 3/30 :: midway check-in due
[ ] 4/11 :: final submission
[ ] 4/16 :: results announced

**Comment by shreyaspapi** [comment]
> [ ] 3/25 :: midway check-in starts
> [ ] 3/30 :: midway check-in due

Due -

- Landing page explaining concept.
- Create a node and deploy it on polkadot.
- Implement qudratic funding/staking. 
- Initial app UI (Finalise the theme from behance/dribbble)

**Comment by thisispalash** [comment]
not submitted. project scope increased beyond imagination.
